### ISSUE TITLE
Sender email ignored when emailing receipt

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#11]
When emailing a receipt, the **CYBSMposReceiptRequest.fromEmail** is being disregarded. Instead of using the value that's set, the sender email keeps falling back to **"CyberSource Customer Support <donotreply@support.cybersource.com>"**.

![2020-01-07 10_32_40-Window](https://user-images.githubusercontent.com/59618262/71919438-89062680-3139-11ea-9ae4-02b92560801e.png)

When I instantiate the **CYBSMposReceiptRequest** object, hard-coding a value for the **fromEmail** property, it doesn't appear to have any effect.

**Comment by cmanjapp** [comment]
Because of some security restrictions we have disabled custom email sending option. All emails will be sent through default  noreply support cybersource email ID. If you need customized email option, then we suggest you to create your own email service and use the transaction response fields.

**Comment by ryanflores-bayalarm** [comment]
Thank you for the reply and the suggestion. We'll move forward with handling the receipt ourselves.
