### ISSUE TITLE
Ability to specify the sender email when emailing a receipt from a transaction

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#13]
When instantiating a **CYBSMposReceiptRequest** object that's needed to email a receipt, the sender's email (via the **fromEmail** property)  could only be specified when instantiating the object via **initWithToEmail**. It would be nice if the sender's email could also be specified when instantiating the object via **initWithTransactionID**.

Once [Issue #11](https://github.com/CyberSource/cybersource-mPOS-sdk-iOS/issues/11) gets resolved, it would be nice to have the ability to specify the sender email when sending a receipt from a transaction so that a custom address will appear on the email header instead of **"CyberSource Customer Support <donotreply@support.cybersource.com>"**.

**Comment by cmanjapp** [comment]
Because of some security restrictions we have disabled custom email sending option. All emails will be sent through default  noreply cybersource email ID. If you need customized email, then we suggest you to create your own email server and use the transaction response fields.

**Comment by ryanflores-bayalarm** [comment]
Thank you for the response. Closing since this is related to #11 and provides the same suggestion.
