### ISSUE TITLE
Email receipts have inconsistent formatting

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#14]
The receipt that gets emailed when sending from a transaction response (via **CYBSMposReceiptRequest::initWithToEmail()**) versus a Transaction/Request ID (via **CYBSMposReceiptRequest::initWithTransactionID()**) appears different. The former contains additional _Payment Information_, while the latter does not.

### EMAIL FROM TRANSACTION RESPONSE

![2020-01-07 10_55_50-Window](https://user-images.githubusercontent.com/59618262/71920802-6cb7b900-313c-11ea-906d-9e65e5f18c46.png)

### EMAIL FROM TRANSACTION/REQUEST ID

![2020-01-07 10_56_27-Window](https://user-images.githubusercontent.com/59618262/71920809-717c6d00-313c-11ea-9857-94504064fe0d.png)

It would be nice if:

- Both receipts were formatted the same
- Developers were given the ability to control whether or not the **Payment Information** and/or the type of information that should be visible on the receipt since most of the information (i.e. the EMV Tags) adds no value for the customer

**Comment by cmanjapp** [comment]
We cant customize (show or hide payment info) or change format of email at this point. If you need customized email, then we suggest you to create your own email server and use the transaction response fields.

**Comment by ryanflores-bayalarm** [comment]
Thank you for the response. Closing since this is related to both #11 and #13, and provides the same suggestion.
