### ISSUE TITLE
NFC fails with the Audio reader

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#20]
When I attempt to take a payment using NFC with the Audio reader, it fails with the following error code and message:

> code: 2020
> message: Invalid account number.

This appears to only happen with the Audio reader; NFC appears to work fine with the Bluetooth reader.

### RECREATE STEPS

- Connect the Audio reader to the iOS device
- Initiate a payment
- Using a device with NFC enabled and configured, tap the device on the Audio reader
- Sign when the signature panel appears

### EXPECTED RESULTS

Transaction completes successfully and returns a success response.

### ACTUAL RESULTS

Transaction gets declined and error code **2020** gets returned, along with the message **Invalid account number.**

**Comment by cmanjapp** [comment]
We have tested and NFC works good for our Audio readers. Could you please check if any reader update is required.
Provide us the failed transactionID through email, so we will verify the request from our end.

**Comment by ryanflores-bayalarm** [comment]
When you say to check for a reader update, I'm assuming you're referring to performing an OTA Update. If so, you just reminded me about an issue I had with that. I was never able to perform an OTA Update, but haven't tried recently and will try again.  If I continue to have problems with that, I report a new issue regarding that matter.

**Comment by ryanflores-bayalarm** [comment]
After performing an *OTA Configuration Update* this morning and attempting the recreate steps, I was no longer able to reproduce this issue. A firmware update wasn't necessary to resolve this issue. Thank you for making the suggestion to update the reader.
