### ISSUE TITLE
Callback needed for failed Bluetooth connection if reader is powered off

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#23]
A callback similar to the Audio reader **onNoAudioDeviceDetected** callback is needed for Bluetooth readers. It would be nice to have an **onNoBTDeviceDetected** callback to handle these two use cases:

1. User connects to a Bluetooth reader using the app, powers off the Bluetooth reader, then calls **getDeviceInfo()**. The **onNoBTDeviceDetected** should get triggered.
2. User performs a scan, then powers on the Bluetooth reader. Once the Bluetooth reader is discovered, user powers off the Bluetooth reader, then taps the discovered reader from the list of available devices. The **onNoBTDeviceDetected** should get triggered. 

For scenario #2, nothing currently happens (**onReturnDeviceError** doesn't even get trigerred) and the spinner shows perpetually until the Bluetooth reader gets powered on and another scan is performed.

**Comment by cmanjapp** [comment]
1. onBTDisconnected() will be called, so no need to call getDeviceInfo(). But in this case you will get onReturnDeviceError callback. 

2.  onBTConnectTimeout() will be called, as it tries to connect the disconnected reader.

**Comment by ryanflores-bayalarm** [comment]
Thank you for the response and suggestions. I somehow overlooked **onBTConnectTimeout()** and will implement that into our app. Thanks.
