### ISSUE TITLE
Ability to omit tax from receipt

### ISSUE THREAD

**Issue by ryanflores-bayalarm** [CyberSource/cybersource-mPOS-sdk-iOS#25]
There are times when tax does not apply. It would be nice if we had the ability to control when tax should appear on receipts.

**Comment by cmanjapp** [comment]
You can add tax to items, please refer getItemsList() in PlaceOrderViewController.

We cant customize or change format of email at this point. If you need customized email, then we suggest you to create your own email server and use the transaction response fields.

**Comment by ryanflores-bayalarm** [comment]
Thank you for the response. Closing since this is related to both #11, #13, and #14, and provides the same suggestion.
